'use client'
import Link from 'next/link'
export default function LandingPage() {
  return (
    <div className="min-h-screen bg-gray-bg">
      <header className="bg-navy text-white shadow-lg"><div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-10 h-10 bg-brand-red rounded-lg flex items-center justify-center font-bold text-white text-lg">P</div><div><h1 className="text-xl font-bold">Pro English BD</h1><p className="text-xs text-gray-300">English to Bangla Translation Practice</p></div></div><div className="flex gap-3"><Link href="/login" className="px-4 py-2 border border-white rounded-lg hover:bg-white hover:text-navy transition text-sm font-medium">লগইন</Link><Link href="/register" className="px-4 py-2 bg-brand-red rounded-lg hover:bg-brand-red-light transition text-sm font-medium">রেজিস্ট্রেশন</Link></div></div></header>
      <section className="bg-gradient-to-br from-navy to-navy-light text-white py-20"><div className="max-w-7xl mx-auto px-4 text-center"><h2 className="text-4xl md:text-5xl font-bold mb-4 bangla-text">ইংরেজি থেকে বাংলা অনুবাদ প্র্যাকটিস</h2><p className="text-lg md:text-xl text-gray-200 mb-8 bangla-text max-w-3xl mx-auto">সহজ বাক্য থেকে শুরু করে IELTS Reading Passage পর্যন্ত — ধাপে ধাপে আপনার ইংরেজি বোঝার দক্ষতা বাড়ান</p><div className="flex gap-4 justify-center flex-wrap"><Link href="/register" className="px-8 py-3 bg-brand-red text-white rounded-xl font-bold text-lg hover:bg-brand-red-light transition shadow-lg">এখনই শুরু করুন →</Link><Link href="/login" className="px-8 py-3 bg-white/10 border-2 border-white text-white rounded-xl font-bold text-lg hover:bg-white/20 transition">লগইন করুন</Link></div></div></section>
      <section className="py-16 max-w-7xl mx-auto px-4"><h3 className="text-3xl font-bold text-center text-navy mb-12 bangla-text">কেন Pro English BD?</h3><div className="grid md:grid-cols-3 gap-8">{[{icon:'📝',title:'ধাপে ধাপে অনুবাদ প্র্যাকটিস',desc:'সহজ বাক্য থেকে জটিল passage পর্যন্ত'},{icon:'📚',title:'ভোকাবুলারী শেখা',desc:'প্রতিটি বাক্যের সাথে শব্দের অর্থ ও উদাহরণ'},{icon:'📊',title:'প্রগ্রেস ট্র্যাকিং',desc:'পয়েন্ট, স্ট্রিক, ব্যাজ সবকিছু'},{icon:'🏆',title:'গ্যামিফিকেশন',desc:'পয়েন্ট, XP, ব্যাজ দিয়ে মোটিভেটেড থাকুন'},{icon:'📋',title:'হোমওয়ার্ক সিস্টেম',desc:'টিচার হোমওয়ার্ক দিবেন, আপনি সম্পন্ন করবেন'},{icon:'🎯',title:'IELTS প্রস্তুতি',desc:'IELTS Reading style passage দিয়ে শিখুন'}].map((f,i)=>(<div key={i} className="bg-white rounded-2xl p-6 shadow-sm card-hover border border-gray-border"><div className="text-4xl mb-4">{f.icon}</div><h4 className="text-lg font-bold text-navy mb-2 bangla-text">{f.title}</h4><p className="text-gray-600 bangla-text text-sm">{f.desc}</p></div>))}</div></section>
      <section className="py-16 bg-navy text-white text-center"><h3 className="text-3xl font-bold mb-4 bangla-text">আজই শুরু করুন!</h3><p className="text-gray-300 mb-8 bangla-text">প্রতিদিন অনুবাদ করুন, শব্দ শিখুন</p><Link href="/register" className="px-8 py-3 bg-brand-red text-white rounded-xl font-bold text-lg hover:bg-brand-red-light transition shadow-lg inline-block">ফ্রি রেজিস্ট্রেশন করুন</Link></section>
      <footer className="bg-navy-dark text-gray-400 py-8"><div className="max-w-7xl mx-auto px-4 text-center"><p className="text-sm">© 2025 Pro English BD. All rights reserved.</p></div></footer>
    </div>
  )
}
